sudo: required
# specify language
language: node_js

# specify language options
node_js:
- '0.10'
- '0.11'

# configure which branches to run
branches:
  # whitelist
  only:
    - master
    - /^deploy-.*$/ # regex ok
  # blacklist
  except:
    - dontrunme
    - test

services:
  - docker

before_install:
  - docker build -t haibui/backend-service ./service/backend-service/

after_success:
  - docker build -t haibui/backend-service ./service/backend-service/
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push service/backend-service
